# get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
 
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$java\
$nodejs\
$python\
$terraform\
$time\
$line_break\
$character"""

add_newline = true
command_timeout = 500

# disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
disabled = false
